// themes/WebGuitarPro_ReactJs/assets/js/Player/components/SongPositionItem.js
import React, { useState } from 'react';

const SongPositionItem = ( {player} ) => {

    const [strCurrentTime, setStrCurrentTime]   = useState( '00:00' );
    const [strEndTime, setStrEndTime]           = useState( '00:00' );
    
    const panelStyle = {
        margin: "0 0 15px 0",
        padding: "5px 10px"
    };
    
    const panelTextStyle = {
        fontSize: "12px",
        fontWeight: "bold",
        whiteSpace: "nowrap"
    };
    
    function formatDuration( milliseconds )
    {
        let seconds     = milliseconds / 1000;
        const minutes   = ( seconds / 60 ) | 0;
        seconds         = ( seconds - minutes * 60 ) | 0;
        return (
            String( minutes ).padStart( 2, "0" ) +
            ":" +
            String( seconds ).padStart( 2, "0" )
        );
    }

    player.playerPositionChanged.on( ( e ) => {
        setStrCurrentTime( formatDuration( e.currentTime ) );
        setStrEndTime( formatDuration( e.endTime ) );
    });
    
    return (
        <div className="displayPanel" style={panelStyle}>
            <div id="song-position" style={panelTextStyle}>{strCurrentTime} / {strEndTime}</div>
        </div>
    );
}

export default SongPositionItem;

// themes/WebGuitarPro_AngularJs/assets/js/Player/tablature-player/player-controls/song-position-item/song-position-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { AlphaTabApi } from '@coderline/alphatab';

@Component({
    selector: 'song-position-item',
    templateUrl: './song-position-item.component.html',
    styleUrls: []
    //styleUrls: ['../player-controls.component.scss']
})
export class SongPositionItemComponent implements OnInit
{
    strCurrentTime: string  = '00:00';
    strEndTime: string      = '00:00';
    
    @Input() player?: AlphaTabApi;
    
    constructor()
    {
        
    }
    
    ngOnInit(): void
    {
        if ( this.player ) {
            this.player.playerPositionChanged.on( ( e: any ) => {
                this.strCurrentTime = this.formatDuration( e.currentTime );
                this.strEndTime     = this.formatDuration( e.endTime );
            });
        }
    }
    
    formatDuration( milliseconds: number )
    {
        let seconds     = milliseconds / 1000;
        const minutes   = ( seconds / 60 ) | 0;
        seconds         = ( seconds - minutes * 60 ) | 0;
        return (
            String( minutes ).padStart( 2, "0" ) +
            ":" +
            String( seconds ).padStart( 2, "0" )
        );
    }

    
}

<div class="displayPanel" 
    style="margin: 0 0 15px 0; padding: 5px 10px;"
>
    <div id="song-position" style="font-size: 12px; font-weight: bold; white-space: nowrap;">
        {{ strCurrentTime }} / {{ strEndTime }}
    </div>
</div>
