// themes/WebGuitarPro_AngularJs/assets/js/Player/tablature-player/player-controls/player-controls.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { AlphaTabApi } from '@coderline/alphatab';

declare var $: any;

@Component({
    selector: 'player-controls',
    templateUrl: './player-controls.component.html',
    styleUrls: []
    //styleUrls: ['./player-controls.component.scss']
})
export class PlayerControlsComponent implements OnInit
{
    @Input() tabId: number = 0;
    @Input() player?: AlphaTabApi;
    
    isLoggedIn: boolean     = false;
    
    constructor()
    {
        let isLogged    = $( '#alphaTab' ).attr( 'data-user' );
        this.isLoggedIn = ( String( isLogged ).toLowerCase() == "true" );
    }
    
    ngOnInit(): void
    {
        
    }  
}

<nav id="sidebar" class="sidebar active">
    
    <!-- Display Song Position -->
    <song-position-item [player]="player" ></song-position-item>
    
    <div class="player-controls displayPanel" style="padding: 5px 10px;">
        
        <!-- PlayPause Button -->
        <play-pause-button-item [player]="player" ></play-pause-button-item>

        <!-- Stop Button -->
        <stop-button-item [player]="player" ></stop-button-item>
        
        <!-- Looping Button -->
        <looping-button-item [player]="player" ></looping-button-item>
        
        <!-- Metronome Button -->
        <metronome-button-item [player]="player" ></metronome-button-item>
        
        <!-- CountIn Button -->
        <count-in-button-item [player]="player" ></count-in-button-item>
        
        <!-- Tracks Button -->
        <tracks-item [player]="player" ></tracks-item>
        
        <!-- Speed Button -->
        <speed-item [player]="player" ></speed-item>
        
        <!-- Layout Button -->
        <layout-item [player]="player" ></layout-item>
        
        <!-- Print Button -->
        <print-item [player]="player" ></print-item>
        
        <!-- Favorites Button -->
        <favorites-button-item *ngIf="isLoggedIn" [tabId]="tabId" ></favorites-button-item>
        
        <!-- Information Button -->
        <information-button-item [player]="player" ></information-button-item>
        
        <!-- Download Button -->
        <download-button-item></download-button-item>
    </div>

</nav>

// themes/WebGuitarPro_VueJs/assets/js/Player/PlayerControls.vue
<template>
    <nav id="sidebar" class="sidebar active">
    
        <!-- Display Song Position -->
        <song-position-item></song-position-item>
            
        <div class="player-controls displayPanel" style="padding: 5px 10px;">
            <!-- PlayPause Button -->
            <div id="btnPlayPause" class="player-controls__item" @click="playPause">
                <svg class="icon">
                    <use xlink:href="#icon-pause-litle" v-if="playerState==1"></use>
                    <use xlink:href="#icon-play-litle" v-else></use>
                </svg>
            </div>
  
            <!-- Stop Button -->
            <div id="btnStop" class="player-controls__item" @click="stop">
                <svg class="icon"><use xlink:href="#icon-stop-new"></use></svg>
            </div>
            
            <!-- Loop Button -->
            <div id="btnLooping" class="player-controls__item" @click="looping">
                <svg class="icon">
                    <use xlink:href="#icon-looping"></use>
                </svg>
            </div>
            
            <!-- Metronome Button -->
            <div id="btnMetronome" class="player-controls__item" @click="metronome">
                <svg class="icon">
                    <use xlink:href="#icon-metronome"></use>
                </svg>
            </div>
             
            <div id="btnCountIn" class="player-controls__item" @click="countIn">
                <svg class="icon">
                    <use xlink:href="#icon-countin"></use>
                </svg>
            </div>
            
            <!-- Tracks Button -->
            <tracks-item v-if="this.PlayerScoreLoaded" v-bind:tracks="this.player.score.tracks"></tracks-item>
            
            <!-- Speed Button -->
            <speed-item></speed-item>
             
            <!-- Layout Button -->
            <layout-item v-if="this.PlayerScoreLoaded"></layout-item>
            
            <!-- Print Button -->
            <print-item v-if="this.PlayerScoreLoaded"></print-item>
            
            <!-- Add to Favorites Button -->
            <div v-if="this.user != 0" id="add-favorite-url" class="player-controls__item favorite" data-url="url_add_to_favorite" @click="favorite">
                <svg class="icon">
                    <use xlink:href="#icon-heart"></use>
                </svg>
            </div>
            
            <!-- Tablature Information Button -->
            <information-item v-if="this.PlayerScoreLoaded"></information-item>
            
        </div>
    </nav>
</template>

<script src="./PlayerControlsScript.js"></script>
