// themes/WebGuitarPro_VueJs/assets/js/Player/components/PrintItem.vue
<template>    
    <div class="player-controls__item" @click="print">
        <svg class="icon">
            <use xlink:href="#icon-print-new"></use>
        </svg>
    </div>
</template>

<script>
export default {
    name: 'print-item',
    data () {
        return {
            
        }
    },
    methods: {
        print() {
            this.$parent.player.print();
        },
    },
}
</script>

// themes/WebGuitarPro_ReactJs/assets/js/Player/components/PrintItem.js
import React from 'react';

const PrintItem = ( {player} ) => {

    function print()
    {
        player.print();
    }
    
    return (
        <div className="player-controls__item" onClick={ print }>
            <svg className="icon">
                <use xlinkHref="#icon-print-new"></use>
            </svg>
        </div>
    );
}

export default PrintItem;
