// themes/WebGuitarPro_VueJs/assets/js/Player/components/PrintItem.vue
<template>    
    <div class="player-controls__item" @click="print">
        <svg class="icon">
            <use xlink:href="#icon-print-new"></use>
        </svg>
    </div>
</template>

<script>
export default {
    name: 'print-item',
    data () {
        return {
            
        }
    },
    methods: {
        print() {
            this.$parent.player.print();
        },
    },
}
</script>

// themes/WebGuitarPro_AngularJs/assets/js/Player/tablature-player/player-controls/print-item/print-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { AlphaTabApi } from '@coderline/alphatab';

declare var $: any;

@Component({
    selector: 'print-item',
    templateUrl: './print-item.component.html',
    styleUrls: ['../player-controls.component.scss']
})
export class PrintItemComponent implements OnInit
{
    @Input() player?: AlphaTabApi;
    
    constructor()
    {
        
    }
    
    ngOnInit(): void
    {
        
    }
    
    printHandler():void
    {
        if ( this.player ) {
            this.player.print();
        }
    }
}

<div class="player-controls__item"
    placement="top"
    ngbTooltip="Print Tablature"
    (click)="printHandler()"
>
    <svg class="icon">
        <use xlink:href="#icon-print-new"></use>
    </svg>
</div>
