// themes/WebGuitarPro_ReactJs/assets/js/Player/components/InformationItem.js
import React from 'react';

import InformationModal from './InformationModal';

const InformationItem = ( {player} ) => {

    function handleClick( e )
    {
        e.preventDefault();
        
        $( '#tabInfo' ).find( '.title' ).text( player.score.title );
        $( '#tabInfo' ).find( '.subTitle' ).text( player.score.subTitle );
        $( '#tabInfo' ).find( '.artist' ).text( player.score.artist );
        
        $( '#tabInfo' ).find( '.album' ).text( player.score.album );
        $( '#tabInfo' ).find( '.copyright' ).text( player.score.copyright );
        $( '#tabInfo' ).find( '.notices' ).text( player.score.notices );
        $( '#tabInfo' ).find( '.words' ).text( player.score.words );
        $( '#tabInfo' ).find( '.music' ).text( player.score.music );
    }
  
    return (
        <div className="player-controls__item">
            <svg className="icon" data-bs-toggle="modal" data-bs-target="#tab-information-modal" onClick={handleClick}>
                <use xlinkHref="#icon-about"></use>
            </svg>
            
            <InformationModal />
        </div>
    );
    
}

export default InformationItem;

// themes/WebGuitarPro_VueJs/assets/js/Player/components/InformationItem.vue
<template>    
    <div class="player-controls__item">
        <svg class="icon" data-bs-toggle="modal" data-bs-target="#tab-information-modal">
            <use xlink:href="#icon-about"></use>
        </svg>
    </div>
</template>

<script>
export default {
    name: 'information-item',
    created: function () {
        /* 
         * https://docs.alphatab.net/master/api/AlphaTab.Model/Score/
         */
        $( '#tabInfo' ).find( '.title' ).text( this.$parent.player.score.title );
        $( '#tabInfo' ).find( '.subTitle' ).text( this.$parent.player.score.subTitle );
        $( '#tabInfo' ).find( '.artist' ).text( this.$parent.player.score.artist );
        
        $( '#tabInfo' ).find( '.album' ).text( this.$parent.player.score.album );
        $( '#tabInfo' ).find( '.copyright' ).text( this.$parent.player.score.copyright );
        $( '#tabInfo' ).find( '.notices' ).text( this.$parent.player.score.notices );
        $( '#tabInfo' ).find( '.words' ).text( this.$parent.player.score.words );
        $( '#tabInfo' ).find( '.music' ).text( this.$parent.player.score.music );
    },
}
</script>
