// themes/WebGuitarPro_ReactJs/assets/js/Player/components/LayoutItem.js
import React, { useState } from 'react';

const LayoutItem = ( {player} ) => {

    const [selectedLayout, setSelectedLayout]               = useState({
        id: 'page',
        text: 'Page',
        layout: 'page',
        scrollmode: 'vertical'
    });
    const [selectedStaveprofile, setSelectedStaveprofile]   = useState({
        staveprofile: alphaTab.StaveProfile.ScoreTab,
        text: 'ScoreTab',
    });
    
    const staveprofiles   =  [
        {
            staveprofile: alphaTab.StaveProfile.Default,
            text: 'Default',
        },
        {
            staveprofile: alphaTab.StaveProfile.ScoreTab,
            text: 'ScoreTab',
        },
        {
            staveprofile: alphaTab.StaveProfile.Score,
            text: 'Score',
        },
        {
            staveprofile: alphaTab.StaveProfile.Tab,
            text: 'Tab',
        },
        {
            staveprofile: alphaTab.StaveProfile.TabMixed,
            text: 'TabMixed',
        }
    ];
    
    const layouts         = [
        {
            id: 'page',
            text: 'Page',
            layout: alphaTab.LayoutMode.Page,
            scrollmode: 'vertical',
        },
        {
            id: 'horizontalBarwise',
            text: 'Horizontal (Barwise)',
            layout: alphaTab.LayoutMode.Horizontal,
            scrollmode: 'horizontal-bar',
        },
        {
            id: 'horizontalOffscreen',
            text: 'Horizontal (Offscreen)',
            layout: alphaTab.LayoutMode.Horizontal,
            scrollmode: 'horizontal-offscreen',
        },
    ];
    
    function setLayout( layout, event )
    {
        if ( layout.id == selectedLayout.id )
            return;
            
        setSelectedLayout( layout );

        player.settings.display.layoutMode = selectedLayout.layout;
        player.updateSettings();
        player.render();
        
        //$( event.target ).closest( ".dropdown-menu" ).toggleClass( 'show' );
    }
    
    function setStaveprofile(  staveprofile, event  )
    {
        if ( staveprofile.staveprofile == selectedStaveprofile.staveprofile )
            return;
            
        setSelectedStaveprofile( staveprofile );
         
        player.settings.display.staveProfile = selectedStaveprofile.staveprofile;
        player.updateSettings();
        player.render();
        
        //$( event.target ).closest( ".dropdown-menu" ).toggleClass( 'show' );
    }


    const layoutsList = layouts.map( ( layout, index ) => (
        <li key={index} className="{ if ( layout.id == selectedLayout.id ) { 'active' } }"
            onClick={ event => setLayout( layout, event ) }
        >{ layout.text }</li>
    ));
    
    const staveprofilesList = staveprofiles.map( ( staveprofile, index ) => (
        <li key={index} className="{ if ( staveprofile == selectedStaveprofile ) { 'active' } }"
            onClick={ event => setStaveprofile( staveprofile, event ) }
        >{ staveprofile.text }</li>
    ));
    
    return (
        <div className="player-controls__item">
            <svg className="icon dropdown-toggle" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
                <use xlinkHref="#icon-layout"></use>
            </svg>
            <div className="dropdown-menu dropdown-menu-right dropright dropup dropdown-layers player-menu-right">
                <div className="dropdown-menu-background">
                
                    <div style={{fontWeight: "bold", paddingLeft: "10px"}}>Layout</div>
                    <ul>{ layoutsList }</ul>
                    
                    <div style={{fontWeight: "bold", paddingLeft: "10px"}}>Stave Profile</div>
                    <ul>{ staveprofilesList }</ul>
                    
                </div>
            </div>
        </div>
    );
}

export default LayoutItem;

// themes/WebGuitarPro_VueJs/assets/js/Player/components/LayoutItem.vue
<template>
    <div class="player-controls__item">
        <svg class="icon dropdown-toggle" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
            <use xlink:href="#icon-layout"></use>
        </svg>
        <div class="dropdown-menu dropdown-menu-right dropright dropup dropdown-layers">
            <div class="dropdown-menu-background">
                <div style="font-weight:bold; padding-left: 10px;">Layout</div>
                <ul>
                    <li :class="{ active:layout.id == selectedLayout }"
                        v-for="(layout, index) in this.layouts"
                        v-on:click.stop="setLayout( layout, $event )"
                    >{{ layout.text }}</li>
                </ul>
                <div style="font-weight:bold; padding-left: 10px;">Stave Profile</div>
                <ul>
                    <li :class="{ active:staveprofile == selectedStaveprofile }"
                        v-for="(staveprofile, index) in this.staveprofiles"
                        v-on:click.stop="setStaveprofile( staveprofile, $event )"
                    >{{ staveprofile }}</li>
                </ul>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'layout-item',
    data () {
        return {
            selectedLayout: 'page',
            selectedStaveprofile: 'default',
            
            layouts: [
                {
                    id: 'page',
                    text: 'Page',
                    layout: 'page',
                    scrollmode: 'vertical',
                },
                {
                    id: 'horizontalBarwise',
                    text: 'Horizontal (Barwise)',
                    layout: 'horizontal',
                    scrollmode: 'horizontal-bar',
                },
                {
                    id: 'horizontalOffscreen',
                    text: 'Horizontal (Offscreen)',
                    layout: 'horizontal',
                    scrollmode: 'horizontal-offscreen',
                },
            ],
            
            staveprofiles: ['default', 'scoretab', 'score', 'tab', 'tabmixed'],
        }
    },
    methods: {
        setLayout:  function( layout, event ) {
            this.selectedLayout = layout.id;
            
            // update renderer
            this.$parent.player.settings.display.layoutMode = layout.layout;
            
            // update player
            //this.$parent.player.alphaTab( 'autoScroll', scrollmode );
            
            this.$parent.player.updateSettings();
            this.$parent.player.render();
            
            $( event.target ).closest( ".dropdown-menu" ).toggleClass( 'show' );
        },
        
        setStaveprofile:  function( staveprofile, event ) {
            this.selectedStaveprofile = staveprofile;
            
            // update renderer
            this.$parent.player.settings.display.staveProfile = staveprofile;
            
            this.$parent.player.updateSettings();
            this.$parent.player.render();
            
            $( event.target ).closest( ".dropdown-menu" ).toggleClass( 'show' );
        },
    },
}
</script>
