// themes/WebGuitarPro_VueJs/assets/js/Player/components/LayoutItem.vue
<template>
    <div class="player-controls__item">
        <svg class="icon dropdown-toggle" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
            <use xlink:href="#icon-layout"></use>
        </svg>
        <div class="dropdown-menu dropdown-menu-right dropright dropup dropdown-layers">
            <div class="dropdown-menu-background">
                <div style="font-weight:bold; padding-left: 10px;">Layout</div>
                <ul>
                    <li :class="{ active:layout.id == selectedLayout }"
                        v-for="(layout, index) in this.layouts"
                        v-on:click.stop="setLayout( layout, $event )"
                    >{{ layout.text }}</li>
                </ul>
                <div style="font-weight:bold; padding-left: 10px;">Stave Profile</div>
                <ul>
                    <li :class="{ active:staveprofile == selectedStaveprofile }"
                        v-for="(staveprofile, index) in this.staveprofiles"
                        v-on:click.stop="setStaveprofile( staveprofile, $event )"
                    >{{ staveprofile }}</li>
                </ul>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'layout-item',
    data () {
        return {
            selectedLayout: 'page',
            selectedStaveprofile: 'default',
            
            layouts: [
                {
                    id: 'page',
                    text: 'Page',
                    layout: 'page',
                    scrollmode: 'vertical',
                },
                {
                    id: 'horizontalBarwise',
                    text: 'Horizontal (Barwise)',
                    layout: 'horizontal',
                    scrollmode: 'horizontal-bar',
                },
                {
                    id: 'horizontalOffscreen',
                    text: 'Horizontal (Offscreen)',
                    layout: 'horizontal',
                    scrollmode: 'horizontal-offscreen',
                },
            ],
            
            staveprofiles: ['default', 'scoretab', 'score', 'tab', 'tabmixed'],
        }
    },
    methods: {
        setLayout:  function( layout, event ) {
            this.selectedLayout = layout.id;
            
            // update renderer
            this.$parent.player.settings.display.layoutMode = layout.layout;
            
            // update player
            //this.$parent.player.alphaTab( 'autoScroll', scrollmode );
            
            this.$parent.player.updateSettings();
            this.$parent.player.render();
            
            $( event.target ).closest( ".dropdown-menu" ).toggleClass( 'show' );
        },
        
        setStaveprofile:  function( staveprofile, event ) {
            this.selectedStaveprofile = staveprofile;
            
            // update renderer
            this.$parent.player.settings.display.staveProfile = staveprofile;
            
            this.$parent.player.updateSettings();
            this.$parent.player.render();
            
            $( event.target ).closest( ".dropdown-menu" ).toggleClass( 'show' );
        },
    },
}
</script>

// themes/WebGuitarPro_VelzonSaas/assets/js/Player/tablature-player/player-controls/layout-item/layout-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { AlphaTabApi, LayoutMode, StaveProfile } from '@coderline/alphatab';

import templateString from './layout-item.component.html'

declare var $: any;

@Component({
    selector: 'layout-item',
    
    template: templateString || 'Template Not Loaded !!!',
    styleUrls: []
})
export class LayoutItemComponent implements OnInit
{
    @Input() player?: AlphaTabApi;
    
    ddClass: string        = "player-menu-right";
    tooltipPlace: string   = "right";
    
    selectedLayout: any = {
        id: 'page',
        text: 'Page',
        layout: LayoutMode.Page,
        scrollmode: 'vertical'
    };
    
    selectedStaveprofile: any   = {
        staveprofile: StaveProfile.ScoreTab,
        text: 'ScoreTab',
    }
    
    layouts: Array<any>         = [
        {
            id: 'page',
            text: 'Page',
            layout: LayoutMode.Page,
            scrollmode: 'vertical',
        },
        {
            id: 'horizontalBarwise',
            text: 'Horizontal (Barwise)',
            layout: LayoutMode.Horizontal,
            scrollmode: 'horizontal-bar',
        },
        {
            id: 'horizontalOffscreen',
            text: 'Horizontal (Offscreen)',
            layout: LayoutMode.Horizontal,
            scrollmode: 'horizontal-offscreen',
        },
    ];
    
    staveprofiles: Array<any>   =  [
        {
            staveprofile: StaveProfile.Default,
            text: 'Default',
        },
        {
            staveprofile: StaveProfile.ScoreTab,
            text: 'ScoreTab',
        },
        {
            staveprofile: StaveProfile.Score,
            text: 'Score',
        },
        {
            staveprofile: StaveProfile.Tab,
            text: 'Tab',
        },
        {
            staveprofile: StaveProfile.TabMixed,
            text: 'TabMixed',
        }
    ];
    
    constructor()
    {
        
    }
    
    ngOnInit(): void
    {
        
    }
    
    ngAfterViewInit(): void
    {
        let windowWidth    = $( window ).width();
        let windowHeight    = $( window ).height();
        let contentViewPort = windowHeight - 300;
        let sidebarHeight   = $( '#PlayerControls' ).height();
        
        if ( sidebarHeight > contentViewPort && windowWidth > windowHeight ) {
            this.tooltipPlace   = "bottom";
        }
        
        if ( windowWidth < windowHeight ) {
            this.ddClass   = "";
            this.tooltipPlace   = "left";
        }
    }

    layoutHandler( layout: any, event: any ): void
    {
        if ( layout.id == this.selectedLayout.id )
            return;
            
        this.selectedLayout = layout;

        if ( this.player ) {
            this.player.settings.display.layoutMode = this.selectedLayout.layout;
            this.player.updateSettings();
            this.player.render();
        }
        //$( event.target ).closest( ".dropdown-menu" ).toggleClass( 'show' );
    }
    
    staveprofileHandler(  staveprofile: any, event: any  ): void
    {
        if ( staveprofile.staveprofile == this.selectedStaveprofile.staveprofile )
            return;
            
        this.selectedStaveprofile   = staveprofile;
        
        if ( this.player ) {
            this.player.settings.display.staveProfile = this.selectedStaveprofile.staveprofile;
            this.player.updateSettings();
            this.player.render();
        }
        //$( event.target ).closest( ".dropdown-menu" ).toggleClass( 'show' );
    }
}

<div class="player-controls__item"
    placement="top"
    ngbTooltip="Tablature Layout" placement="{{ tooltipPlace }}"
>
    <svg class="icon dropdown-toggle" data-bs-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
        <use xlink:href="#icon-layout"></use>
    </svg>
    <div class="{{'dropdown-menu dropdown-menu-right dropright dropup ' + ddClass}}">
        <div id="layoutSelector" class="dropdown-menu-background">
        
            <div style="font-weight: bold; padding-left: 10px;">Layout</div>
            <ul>
                <li *ngFor="let layout of layouts"
                    [ngClass]="layout.id == selectedLayout.id ? 'active' : ''"
		            (click)="layoutHandler( layout, $event )"
		        >{{ layout.text }}</li>
            </ul>
            
            <div style="font-weight: bold; padding-left: 10px;">Stave Profile</div>
            <ul>
                <li *ngFor="let staveprofile of staveprofiles"
                    [ngClass]="staveprofile.staveprofile == selectedStaveprofile.staveprofile ? 'active' : ''"
		            (click)="staveprofileHandler( staveprofile, $event )"
		        >{{ staveprofile.text }}</li>
            </ul>
            
        </div>
    </div>
</div>
