// themes/WebGuitarPro_VueJs/assets/js/Player/PlayerControls.vue
<template>
    <nav id="sidebar" class="sidebar active">
    
        <!-- Display Song Position -->
        <song-position-item></song-position-item>
            
        <div class="player-controls displayPanel" style="padding: 5px 10px;">
            <!-- PlayPause Button -->
            <div id="btnPlayPause" class="player-controls__item" @click="playPause">
                <svg class="icon">
                    <use xlink:href="#icon-pause-litle" v-if="playerState==1"></use>
                    <use xlink:href="#icon-play-litle" v-else></use>
                </svg>
            </div>
  
            <!-- Stop Button -->
            <div id="btnStop" class="player-controls__item" @click="stop">
                <svg class="icon"><use xlink:href="#icon-stop-new"></use></svg>
            </div>
            
            <!-- Loop Button -->
            <div id="btnLooping" class="player-controls__item" @click="looping">
                <svg class="icon">
                    <use xlink:href="#icon-looping"></use>
                </svg>
            </div>
            
            <!-- Metronome Button -->
            <div id="btnMetronome" class="player-controls__item" @click="metronome">
                <svg class="icon">
                    <use xlink:href="#icon-metronome"></use>
                </svg>
            </div>
             
            <div id="btnCountIn" class="player-controls__item" @click="countIn">
                <svg class="icon">
                    <use xlink:href="#icon-countin"></use>
                </svg>
            </div>
            
            <!-- Tracks Button -->
            <tracks-item v-if="this.PlayerScoreLoaded" v-bind:tracks="this.player.score.tracks"></tracks-item>
            
            <!-- Speed Button -->
            <speed-item></speed-item>
             
            <!-- Layout Button -->
            <layout-item v-if="this.PlayerScoreLoaded"></layout-item>
            
            <!-- Print Button -->
            <print-item v-if="this.PlayerScoreLoaded"></print-item>
            
            <!-- Add to Favorites Button -->
            <div v-if="this.user != 0" id="add-favorite-url" class="player-controls__item favorite" data-url="url_add_to_favorite" @click="favorite">
                <svg class="icon">
                    <use xlink:href="#icon-heart"></use>
                </svg>
            </div>
            
            <!-- Tablature Information Button -->
            <information-item v-if="this.PlayerScoreLoaded"></information-item>
            
        </div>
    </nav>
</template>

<script src="./PlayerControlsScript.js"></script>

// themes/WebGuitarPro_ReactJs/assets/js/Player/PlayerControls.js
import React, { useEffect, useState } from 'react';

import InformationItem from './components/InformationItem';
import LayoutItem from './components/LayoutItem';
import PrintItem from './components/PrintItem';
import SongPositionItem from './components/SongPositionItem';
import SpeedItem from './components/SpeedItem';
import TracksItem from './components/TracksItem';

const PlayerControls = ( {player, logged} ) => {
    const [playerScoreLoaded, setPlayerScoreLoaded] = useState( false );
    const [playerState, setPlayerState]             = useState( null );
    const [loopingState, setLoopingState]           = useState( null );
    
    let metronomeVolume = null;
    let countInVolume   = null;
    
    useEffect(() => {
        player.playerStateChanged.on( ( args ) => {
            setPlayerState( args.state );
        });
        
        player.scoreLoaded.on( score => {
            setPlayerScoreLoaded( true );
        });
    }, []);
        
    function playPause() {
        if ( ! playerState )
            $( '#btnPlayPause' ).addClass( 'player-control-active  -xl' );
 
        player.playPause();
    }
 
    function stop() {
        player.stop();
 
        $( '#btnPlayPause' ).removeClass( 'player-control-active  -xl' );
    }
    
    function metronome() {
        metronomeVolume    = player.metronomeVolume;
        $( '#btnMetronome' ).toggleClass( 'player-control-active  -xl' );
        player.metronomeVolume = 1;
     
        if( metronomeVolume == 0 ) {
            player.metronomeVolume = 4;
        } else {
            player.metronomeVolume = 0;
        }
    }

    function countIn() {
        countInVolume    = player.countInVolume;
        $( '#btnCountIn' ).toggleClass( 'player-control-active  -xl' );
    
        if( countInVolume == 0 ) {
            player.countInVolume = 4;
        } else {
            player.countInVolume = 0;
        }
    }

    function favorite() {         
        $.get( $( '#add-favorite-url' ).data( 'url' ), function( data ) {
            //alert('This Tab is Added To Favorite List !!!');
            console.log( 'This Tab is Added To Favorite List !!!' );
            document.location.reload();
        });
    }
    
    function loopingHandler() {
        setLoopingState( ! player.isLooping );

        $( '#btnLooping' ).toggleClass( "player-control-active  -xl" );
        player.isLooping    = loopingState;
    }
    
    return (
        <nav id="sidebar" className="sidebar active">
    
            {/* Display Song Position */}
            <SongPositionItem player={player} />
            
            <div className="player-controls displayPanel" style={{padding: "5px 10px"}}>
                
                {/* PlayPause Button */}
                <div id="btnPlayPause" className="player-controls__item" onClick={playPause}>
                    <svg className="icon" style={{fontSize: "50px"}}>
                        { ( playerState == 1 ) ? (
                            <use xlinkHref="#icon-pause-litle"></use>
                        ) : (
                            <use xlinkHref="#icon-play-litle"></use>
                        ) }
                    </svg>
                </div>
      
                {/* Stop Button */}
                <div id="btnStop" className="player-controls__item" onClick={stop}>
                    <svg className="icon"><use xlinkHref="#icon-stop-new"></use></svg>
                </div>
                
                {/* Looping Button */}
                <div id="btnLooping" className="player-controls__item" onClick={loopingHandler}>
                    <svg className="icon" style={{fontSize: "50px"}}>
                        <use xlinkHref="#icon-looping"></use>
                    </svg>
                </div>
                
                {/* Metronome Button */}
                <div id="btnMetronome" className="player-controls__item" onClick={metronome}>
                    <svg className="icon" style={{fontSize: "50px"}}>
                        <use xlinkHref="#icon-metronome"></use>
                    </svg>
                </div>
                 
                <div id="btnCountIn" className="player-controls__item" onClick={countIn}>
                    <svg className="icon" style={{fontSize: "50px"}}>
                        <use xlinkHref="#icon-countin"></use>
                    </svg>
                </div>
                
                {/* Tracks Button */}
                { ( playerScoreLoaded ) ? (
                    <TracksItem player={player} />
                ) : '' }
                
                {/* Speed Button */}
                <SpeedItem player={player} />
                
                {/* Layout Button */}
                <LayoutItem player={player} />
                
                {/* Print Button */}
                <PrintItem player={player} />
                
                {/* Add to Favorites Button */}
                { ( logged ) ? (
                    <div className="player-controls__item favorite" onClick={favorite}>
                        <svg className="icon">
                            <use xlinkHref="#icon-heart"></use>
                        </svg>
                    </div>
                ) : '' }
                
                {/* Tablature Information Button */}
                <InformationItem player={player} />
                
            </div>
        </nav>
    );
}

export default PlayerControls;
